version: "3.8"

services:
  recipe-api:
    build: .
    container_name: recipe-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api",
        ]
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 40s
